namespace jam.net.fb;

enum fbWorldRequestAction : ubyte
{
	AutoAssign  = 0,
	Join		= 1,
	Leave		= 2,
	Transfer	= 3
}

table fbRequestWorldAssignmentReq
{
	action						: fbWorldRequestAction = AutoAssign;
	target_world_id				: uint	= 0;
	target_world_kind			: ubyte = 0;
	target_world_template_id	: uint  = 0;
	target_world_instance_id	: ulong = 0;
}

table fbRequestWorldAssignmentRes
{
	status				: ubyte		= 2;		// ASSIGNED(0), WAITING(1), FAILED(2)
	request_action		: ubyte		= 0;
	assignment_action	: ubyte		= 0;
	reason				: ubyte		= 0;
	world_id			: uint		= 0;
}

root_type fbRequestWorldAssignmentReq;
