namespace jam.net.fb;

enum fbWorldAction : ubyte
{
	AutoAssign  = 0,
	Join		= 1,
	Leave		= 2,
	Transfer	= 3,
	Promote		= 4
}

enum fbWorldMembershipDeltaOp : ubyte
{
	Upsert		= 0,
	Remove		= 1
}

table fbWorldMembershipDelta
{
	op					: fbWorldMembershipDeltaOp = Upsert;
	key_desc_id			: uint		= 0;
	key_world_id		: ulong		= 0;	// authoritative NetWorldId
	kind				: ubyte		= 0;
	role				: ubyte		= 0;
	presence			: ubyte		= 0;
}

table fbWorldRuntimeDelta
{
	key_desc_id			: uint		= 0;
	key_world_id		: ulong		= 0;	// authoritative NetWorldId
	runtime				: ubyte		= 0;
}

table fbWorldActionReq
{
	action				: fbWorldAction = AutoAssign;
	src_desc_id			: uint = 0;
	src_world_id		: ulong = 0;
	target_desc_id		: uint  = 0;
	target_world_id	    : ulong = 0;
}

table fbWorldActionRes
{
	status				: ubyte		= 2;		// SUCCEEDED(0), FAILED(2)
	reason				: ubyte		= 0;
	request_action		: ubyte		= 0;
	exec_flags			: ubyte		= 0;
	src_desc_id			: uint		= 0;
	src_world_id		: ulong		= 0;
	target_desc_id		: uint		= 0;
	target_world_id		: ulong		= 0;
	membership_deltas	: [fbWorldMembershipDelta];
	world_runtime_deltas: [fbWorldRuntimeDelta];
}

root_type fbWorldActionReq;
