#include "Emit/CSharpEmitter.h"
#include "Emit/CSharpTypeMapper.h"
#include "IO/FileIO.h"
#include "Naming/NameConverter.h"

#include <sstream>
#include <unordered_set>

namespace jam::tool
{
	namespace
	{
		const SchemaEnumType* FindNestedEnumType(const SchemaType& type)
		{
			switch (type.kind)
			{
			case eSchemaTypeKind::Enum:
				return &static_cast<const SchemaEnumType&>(type);

			case eSchemaTypeKind::Array:
				return FindNestedEnumType(*static_cast<const SchemaArrayType&>(type).elementType);

			case eSchemaTypeKind::Map:
				return FindNestedEnumType(*static_cast<const SchemaMapType&>(type).valueType);

			default:
				return nullptr;
			}
		}

		void CollectPolymorphicTypesFromType(
			const SchemaType& type,
			std::vector<const SchemaPolymorphicType*>& outTypes,
			std::unordered_set<std::string>& seenBaseNames)
		{
			switch (type.kind)
			{
			case eSchemaTypeKind::Array:
			{
				const auto& arrayType = static_cast<const SchemaArrayType&>(type);
				CollectPolymorphicTypesFromType(*arrayType.elementType, outTypes, seenBaseNames);
				return;
			}

			case eSchemaTypeKind::Map:
			{
				const auto& mapType = static_cast<const SchemaMapType&>(type);
				CollectPolymorphicTypesFromType(*mapType.valueType, outTypes, seenBaseNames);
				return;
			}

			case eSchemaTypeKind::Polymorphic:
			{
				const auto& polymorphicType = static_cast<const SchemaPolymorphicType&>(type);

				if (seenBaseNames.insert(polymorphicType.baseTypeName).second)
					outTypes.push_back(&polymorphicType);

				return;
			}

			default:
				return;
			}
		}

		std::vector<const SchemaPolymorphicType*> CollectPolymorphicTypes(const SchemaDocument& document)
		{
			std::vector<const SchemaPolymorphicType*> polymorphicTypes;
			std::unordered_set<std::string> seenBaseNames;

			for (const auto& object : document.objects)
			{
				for (const auto& field : object.fields)
				{
					CollectPolymorphicTypesFromType(*field.type, polymorphicTypes, seenBaseNames);
				}
			}

			return polymorphicTypes;
		}

		std::string FindBaseTypeForObject(const SchemaDocument& document, const std::string& objectTypeName)
		{
			for (const auto* polymorphicType : CollectPolymorphicTypes(document))
			{
				for (const auto& branch : polymorphicType->branches)
				{
					if (branch.objectTypeName == objectTypeName)
						return polymorphicType->baseTypeName;
				}
			}

			return {};
		}
	}

	void CSharpEmitter::Emit(const SchemaDocument& document, const EmitOptions& options, DiagnosticBag& diagnostics)
	{
		const std::string text = EmitFile(document, options);
		const auto outputPath = options.outputDirectory / MakeOutputFileName(document);

		try
		{
			FileIO::WriteAllText(outputPath, text);
		}
		catch (const std::exception& e)
		{
			diagnostics.Error("CSHARP_EMIT_FAILED", "Failed to emit C# file: " + outputPath.string() + "\n" + e.what());
		}
	}

	std::string CSharpEmitter::EmitFile(const SchemaDocument& document, const EmitOptions& options) const
	{
		std::ostringstream os;

		os << "// This file is generated by jam_shared_data_tool.\n";
		os << "// Do not modify this file manually.\n\n";
		os << "#nullable enable\n\n";

		os << "using System;\n";
		os << "using System.Runtime.Serialization;\n";
		os << "using System.Collections.Generic;\n";
		os << "using Newtonsoft.Json;\n";
		os << "using Newtonsoft.Json.Converters;\n";
		os << "using Newtonsoft.Json.Linq;\n\n";

		os << "namespace " << options.csharpNamespace << "\n";
		os << "{\n";

		os << EmitPolymorphicBases(document);

		for (const auto& object : document.objects)
		{
			os << EmitEnums(object);
		}

		for (const auto& object : document.objects)
		{
			os << EmitObject(document, object);
			os << "\n";
		}

		os << EmitPolymorphicConverters(document);

		os << "}\n";

		return os.str();
	}

	std::string CSharpEmitter::EmitPolymorphicBases(const SchemaDocument& document) const
	{
		std::ostringstream os;

		for (const auto* polymorphicType : CollectPolymorphicTypes(document))
		{
			os << EmitPolymorphicBase(*polymorphicType);
			os << "\n";
		}

		return os.str();
	}

	std::string CSharpEmitter::EmitPolymorphicBase(const SchemaPolymorphicType& polymorphicType) const
	{
		std::ostringstream os;
		os << "    [JsonConverter(typeof(" << polymorphicType.baseTypeName << "JsonConverter))]\n";
		os << "    public abstract class " << polymorphicType.baseTypeName << "\n";
		os << "    {\n";
		os << "    }\n";
		return os.str();
	}

	std::string CSharpEmitter::EmitPolymorphicConverters(const SchemaDocument& document) const
	{
		std::ostringstream os;

		for (const auto* polymorphicType : CollectPolymorphicTypes(document))
		{
			os << EmitPolymorphicConverter(*polymorphicType);
			os << "\n";
		}

		return os.str();
	}

	std::string CSharpEmitter::EmitPolymorphicConverter(const SchemaPolymorphicType& polymorphicType) const
	{
		std::ostringstream os;
		const std::string converterName = polymorphicType.baseTypeName + "JsonConverter";

		os << "    public sealed class " << converterName << " : JsonConverter\n";
		os << "    {\n";
		os << "        public override bool CanConvert(Type objectType)\n";
		os << "        {\n";
		os << "            return objectType == typeof(" << polymorphicType.baseTypeName << ");\n";
		os << "        }\n\n";

		os << "        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)\n";
		os << "        {\n";
		os << "            var token = JToken.Load(reader);\n";
		os << "            if (token.Type == JTokenType.Null)\n";
		os << "                return null;\n\n";
		os << "            var obj = (JObject)token;\n";
		os << "            var discriminator = obj[\"" << polymorphicType.discriminatorField << "\"]?.Value<string>();\n";
		os << "            if (string.IsNullOrEmpty(discriminator))\n";
		os << "                throw new JsonSerializationException(\"Missing discriminator '" << polymorphicType.discriminatorField << "' for " << polymorphicType.baseTypeName << ".\");\n\n";
		os << "            var nestedSerializer = new JsonSerializer();\n";
		os << "            foreach (var converter in serializer.Converters)\n";
		os << "            {\n";
		os << "                if (converter is not " << converterName << ")\n";
		os << "                    nestedSerializer.Converters.Add(converter);\n";
		os << "            }\n";
		os << "            nestedSerializer.ContractResolver = serializer.ContractResolver;\n";
		os << "            nestedSerializer.Culture = serializer.Culture;\n";
		os << "            nestedSerializer.DateFormatHandling = serializer.DateFormatHandling;\n";
		os << "            nestedSerializer.DateParseHandling = serializer.DateParseHandling;\n";
		os << "            nestedSerializer.DateTimeZoneHandling = serializer.DateTimeZoneHandling;\n";
		os << "            nestedSerializer.DefaultValueHandling = serializer.DefaultValueHandling;\n";
		os << "            nestedSerializer.FloatFormatHandling = serializer.FloatFormatHandling;\n";
		os << "            nestedSerializer.FloatParseHandling = serializer.FloatParseHandling;\n";
		os << "            nestedSerializer.Formatting = serializer.Formatting;\n";
		os << "            nestedSerializer.MaxDepth = serializer.MaxDepth;\n";
		os << "            nestedSerializer.MetadataPropertyHandling = serializer.MetadataPropertyHandling;\n";
		os << "            nestedSerializer.MissingMemberHandling = serializer.MissingMemberHandling;\n";
		os << "            nestedSerializer.NullValueHandling = serializer.NullValueHandling;\n";
		os << "            nestedSerializer.ObjectCreationHandling = serializer.ObjectCreationHandling;\n";
		os << "            nestedSerializer.PreserveReferencesHandling = serializer.PreserveReferencesHandling;\n";
		os << "            nestedSerializer.ReferenceLoopHandling = serializer.ReferenceLoopHandling;\n";
		os << "            nestedSerializer.StringEscapeHandling = serializer.StringEscapeHandling;\n";
		os << "            nestedSerializer.TypeNameHandling = serializer.TypeNameHandling;\n\n";

		for (const auto& branch : polymorphicType.branches)
		{
			os << "            if (discriminator == \"" << branch.discriminatorValue << "\")\n";
			os << "            {\n";
			os << "                var result = new " << branch.objectTypeName << "();\n";
			os << "                using var subReader = obj.CreateReader();\n";
			os << "                nestedSerializer.Populate(subReader, result);\n";
			os << "                return result;\n";
			os << "            }\n";
		}

		os << "\n";
		os << "            throw new JsonSerializationException(\"Unknown discriminator for " << polymorphicType.baseTypeName << ": \" + discriminator);\n";
		os << "        }\n\n";

		os << "        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)\n";
		os << "        {\n";
		os << "            if (value is null)\n";
		os << "            {\n";
		os << "                writer.WriteNull();\n";
		os << "                return;\n";
		os << "            }\n\n";

		for (const auto& branch : polymorphicType.branches)
		{
			os << "            if (value is " << branch.objectTypeName << " " << NameConverter::ToCamelCase(branch.objectTypeName) << "Value)\n";
			os << "            {\n";
			os << "                serializer.Serialize(writer, " << NameConverter::ToCamelCase(branch.objectTypeName) << "Value);\n";
			os << "                return;\n";
			os << "            }\n";
		}

		os << "\n";
		os << "            throw new JsonSerializationException(\"Unknown runtime type for " << polymorphicType.baseTypeName << ".\");\n";
		os << "        }\n";
		os << "    }\n";

		return os.str();
	}

	std::string CSharpEmitter::EmitEnums(const SchemaObject& object) const
	{
		std::ostringstream os;

		for (const auto& field : object.fields)
		{
			if (!FindNestedEnumType(*field.type))
				continue;

			os << EmitEnum(object, field);
			os << "\n";
		}

		return os.str();
	}

	std::string CSharpEmitter::EmitEnum(const SchemaObject& object, const SchemaField& field) const
	{
		const auto* enumType = FindNestedEnumType(*field.type);
		if (!enumType)
			return {};

		const std::string enumTypeName = CSharpTypeMapper::MakeFieldLocalEnumTypeName(object, field);
		std::ostringstream os;

		os << "    [JsonConverter(typeof(StringEnumConverter))]\n";
		os << "    public enum " << enumTypeName << "\n";
		os << "    {\n";

		for (std::size_t i = 0; i < enumType->values.size(); ++i)
		{
			os << "        [EnumMember(Value = \"" << enumType->values[i] << "\")]\n";
			os << "        " << NameConverter::ToCSharpEnumMemberName(enumType->values[i]);

			if (i + 1 < enumType->values.size())
				os << ",";

			os << "\n";
		}

		os << "    }\n";

		return os.str();
	}

	std::string CSharpEmitter::EmitObject(const SchemaDocument& document, const SchemaObject& object) const
	{
		std::ostringstream os;
		const std::string baseTypeName = FindBaseTypeForObject(document, object.name);

		os << "    public sealed class " << object.name;

		if (!baseTypeName.empty())
			os << " : " << baseTypeName;

		os << "\n";
		os << "    {\n";

		for (const auto& field : object.fields)
		{
			os << "        [JsonProperty(\"" << field.jsonName << "\"";

			if (field.required)
				os << ", Required = Required.Always";

			os << ")]\n";

			os << "        public " << CSharpTypeMapper::MapFieldType(object, field) << " " << field.csharpName << " { get; set; }";

			const std::string defaultValue = EmitPropertyDefaultValue(field);

			if (!defaultValue.empty())
				os << " = " << defaultValue << ";";

			os << "\n\n";
		}

		os << "    }\n";

		return os.str();
	}

	std::string CSharpEmitter::EmitPropertyDefaultValue(const SchemaField& field) const
	{
		const auto& type = *field.type;

		switch (type.kind)
		{
		case eSchemaTypeKind::Primitive:
		{
			const auto& primitive = static_cast<const SchemaPrimitiveType&>(type);

			switch (primitive.primitive)
			{
			case eSchemaPrimitiveKind::String:
				return "string.Empty";

			case eSchemaPrimitiveKind::Integer:
			case eSchemaPrimitiveKind::Number:
			case eSchemaPrimitiveKind::Boolean:
				return "";
			}

			break;
		}

		case eSchemaTypeKind::Array:
		case eSchemaTypeKind::Map:
			return "new()";

		case eSchemaTypeKind::ObjectRef:
			return "new()";

		case eSchemaTypeKind::Enum:
		case eSchemaTypeKind::Polymorphic:
		case eSchemaTypeKind::Custom:
			return "";

		default:
			break;
		}

		return "";
	}

	std::string CSharpEmitter::MakeOutputFileName(const SchemaDocument& document) const
	{
		const auto stem = document.srcPath.stem().string();

		if (stem.ends_with(".schema"))
			return stem.substr(0, stem.size() - 7) + ".g.cs";

		return stem + ".g.cs";
	}
}
