include "physics_type.fbs";
include "snapshot.fbs";

namespace jam.net.fb;



table fbSpawnActorReq
{
	spawn_req_id			: uint;
	owner_user_id			: ulong;
	controller_user_id		: ulong;

	prefab_key				: ulong;
	pos						: fbVec3;
	rot						: fbQuat;
	spawn_src				: uint;		// 0 : level, 1: runtime, 2: network, 3: tool
	team_id					: uint;
	part_id					: uint;
	role_id					: uint;
	
	override_mask 			: uint;		// bitmask for override fields below
	linear_vel				: fbVec3;
	angular_vel				: fbVec3;
	linear_damping			: float;
	angular_damping			: float;
	yaw						: float;
	pitch					: float;
}

table fbSpawnActorRes
{
	success				: bool;
	spawn_req_id		: ulong;
	net_id				: uint;
}

table fbDespawnActorReq
{
	net_id				: uint;
}

table fbDespawnActorRes
{
	success				: bool;
}

root_type fbSpawnActorReq;
file_identifier "SPAW";