namespace jam.net.fb;



struct fbTransformDelta
{
	data0				: ulong;
	data1				: ulong;
}

struct fbTransformFull
{
	data0				: ulong;
	data1				: ulong;
	data2				: ulong;
}

struct fbCharacterFull128
{
	data0 : ulong;
	data1 : ulong;
}

struct fbCharacterFull160
{
	data0 : uint;
	data1 : uint;
	data2 : uint;
	data3 : uint;
	data4 : uint;
}

struct fbCharacterDelta96
{
	data0 : uint;
	data1 : uint;
	data2 : uint;
}

struct fbCharacterDelta128
{
	data0 : ulong;
	data1 : ulong;
}

struct fbKinematicState
{
	start_epoch : ulong;
	phase		: uint;
	t			: float;
	target_id	: uint;
	event_mask	: uint;
	kine_type	: ubyte;
}

enum fbRemovalReason : ubyte
{
	AoiLeft = 0,
	Destroyed = 1
}

table fbRemovedActor
{
	net_id				: uint;
	reason				: fbRemovalReason = AoiLeft;
}


// --- Snapshot --- 

table fbSnapshotHeader
{
	server_tick			: uint;
	input_ack			: uint;
	input_epoch			: uint;
	chunk_index			: ushort = 0;
	chunk_count			: ushort = 1;
	global_keyframe		: bool = false;
}



table fbActorMeta
{
	owner_user_id		: ulong = 0;		
	controller_user_id	: ulong = 0;		
	actor_archetype_key	: ulong = 0;
	spawn_req_id		: uint  = 0;
	packed_id			: uint  = 0;	// team(16) / part(8) / role (8)
	body_type			: ubyte = 0;
}


table fbActorEntity
{
	net_id				: uint;
	baseline_rev		: uint;

	transform_full		: fbTransformFull;
	transform_delta		: fbTransformDelta;

	character_full		: fbCharacterFull160;
	character_delta		: fbCharacterDelta128;

	kinematic_state		: fbKinematicState;
}

table fbSnapshot
{
	world_id			: ulong;
	header				: fbSnapshotHeader;
	entities			: [fbActorEntity];
}

root_type fbSnapshot;
file_identifier "SNAP";
